# Generated by Django 4.1.7 on 2023-03-05 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='main',
            old_name='loss',
            new_name='Loss',
        ),
        migrations.RenameField(
            model_name='main',
            old_name='win',
            new_name='Win',
        ),
    ]
