# Generated by Django 4.1.7 on 2023-03-10 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_rename_loss_main_loss_rename_win_main_win'),
    ]

    operations = [
        migrations.RenameField(
            model_name='main',
            old_name='Loss',
            new_name='Points',
        ),
        migrations.RemoveField(
            model_name='main',
            name='Win',
        ),
    ]
